import db from "@/db";
import * as schema from "./schema";

await db.insert(schema.wordBook).values([
  {
    id: "-1",
  },
  {
    id: "1",
    name: "普通高中西班牙语课程标准",
    description: "普通高中西班牙语课程标准",
    total: 100,
    tag: "高中",
    cover:
      "https://spanish-hhw.oss-cn-shanghai.aliyuncs.com/system/ModernSpanish.jpg",
  },
  {
    id: "2",
    name: "普通高中西班牙语课程标准222",
    description: "普通高中西班牙语课程标准222",
    total: 100,
    tag: "高中",
    cover:
      "https://spanish-hhw.oss-cn-shanghai.aliyuncs.com/system/ModernSpanish.jpg",
  },
  {
    id: "3",
    name: "DELE A1",
    description: "DELE A1",
    total: 406,
    tag: "A1",
    cover:
      "https://spanish-hhw.oss-cn-shanghai.aliyuncs.com/system/DELE-A1.jpg",//临时取的名字
  },
]);

await db.insert(schema.word).values([
  {
    id: "1",
    pos: "adj.",
    word: "gordo",
    definition: "definition",
    translation: "胖的",
  },
  {
    id: "2",
    pos: "adj.",
    word: "delgado",
    definition: "definition",
    translation: "瘦的",
  },
  {
    id: "3",
    pos: "adj.",
    word: "alto",
    definition: "definition",
    translation: "高的",
  },
  {
    id: "4",
    pos: "m.",
    word: "pelo",
    definition: "definition",
    translation: "头发, 毛发",
  },
  {
    id: "5",
    pos: "m.",
    word: "ojo",
    definition: "definition",
    translation: "眼睛",
  },
  {
    id: "6",
    pos: "f.",
    word: "nariz",
    definition: "definition",
    translation: "鼻子",
  },
  {
    id: "7",
    pos: "adj.",
    word: "bajo",
    definition: "definition",
    translation: "矮的，低的",
  },
  {
    id: "8",
    pos: "adj.",
    word: "guapo",
    definition: "definition",
    translation: "漂亮的m.,f. 帅哥，美女",
  },
  {
    id: "9",
    pos: "adj.",
    word: "feo",
    definition: "definition",
    translation: "丑的",
  },
  {
    id: "10",
    pos: "n/a",
    word: "pelo rubio",
    definition: "definition",
    translation: "金头发",
  },
  {
    id: "11",
    pos: "n/a",
    word: "tener barba",
    definition: "definition",
    translation: "有胡须",
  },
  {
    id: "12",
    pos: "n/a",
    word: "tener bigote",
    definition: "definition",
    translation: "有髭（上唇至人中部位的胡子）",
  },
  {
    id: "13",
    pos: "n/a",
    word: "llevar gafas",
    definition: "definition",
    translation: "戴眼镜",
  },
  {
    id: "14",
    pos: "n/a",
    word: "tener los ojos grandes",
    definition: "definition",
    translation: "有大眼睛",
  },
  {
    id: "15",
    pos: "n/a",
    word: "tener los ojos pequeños",
    definition: "definition",
    translation: "有小眼睛",
  },
  {
    id: "16",
    pos: "n/a",
    word: "levantarse",
    definition: "definition",
    translation: "prnl. 起床，起身",
  },
  {
    id: "17",
    pos: "adj.",
    word: "simpático",
    definition: "definition",
    translation: "和蔼可亲的",
  },
  {
    id: "18",
    pos: "adj.",
    word: "antipático",
    definition: "definition",
    translation: "令人厌恶的",
  },
  {
    id: "19",
    pos: "adj.",
    word: "inteligente",
    definition: "definition",
    translation: "聪明的",
  },
  {
    id: "20",
    pos: "adj.",
    word: "trabajador",
    definition: "definition",
    translation: "勤劳的",
  },
  {
    id: "21",
    pos: "adj.",
    word: "alegre",
    definition: "definition",
    translation: "高兴的，愉悦的，开朗的",
  },
  {
    id: "22",
    pos: "adj.",
    word: "serio",
    definition: "definition",
    translation: "严肃的",
  },
  {
    id: "23",
    pos: "adj.",
    word: "tímido",
    definition: "definition",
    translation: "害羞的，胆怯的",
  },
  {
    id: "24",
    pos: "adj.",
    word: "sociable",
    definition: "definition",
    translation: "爱社交的",
  },
  {
    id: "25",
    pos: "m.",
    word: "nombre",
    definition: "definition",
    translation: "名字",
  },
  {
    id: "26",
    pos: "n/a",
    word: "primer apellido",
    definition: "definition",
    translation: "第一姓氏",
  },
  {
    id: "27",
    pos: "n/a",
    word: "segundo apellido",
    definition: "definition",
    translation: "第二姓氏",
  },
  {
    id: "28",
    pos: "m.",
    word: "señor",
    definition: "definition",
    translation: "先生",
  },
  {
    id: "29",
    pos: "f.",
    word: "señora",
    definition: "definition",
    translation: "女士",
  },
  {
    id: "30",
    pos: "n/a",
    word: "firmar",
    definition: "definition",
    translation: "tr. 签字",
  },
  {
    id: "31",
    pos: "n/a",
    word: "llamarse",
    definition: "definition",
    translation: "prnl. 叫…名字",
  },
  {
    id: "32",
    pos: "f.",
    word: "dirección",
    definition: "definition",
    translation: "地址",
  },
  {
    id: "33",
    pos: "n/a",
    word: "correo electrónico",
    definition: "definition",
    translation: "电子邮件",
  },
  {
    id: "34",
    pos: "f.",
    word: "calle",
    definition: "definition",
    translation: "街",
  },
  {
    id: "35",
    pos: "f.",
    word: "avenida",
    definition: "definition",
    translation: "大道",
  },
  {
    id: "36",
    pos: "m.",
    word: "paseo",
    definition: "definition",
    translation: "步行道，散步",
  },
  {
    id: "37",
    pos: "m.",
    word: "número",
    definition: "definition",
    translation: "数字，号码",
  },
  {
    id: "38",
    pos: "n/a",
    word: "código postal",
    definition: "definition",
    translation: "邮政编码",
  },
  {
    id: "39",
    pos: "m.",
    word: "país",
    definition: "definition",
    translation: "国家",
  },
  {
    id: "40",
    pos: "f.",
    word: "ciudad",
    definition: "definition",
    translation: "城市",
  },
  {
    id: "41",
    pos: "m.",
    word: "pueblo",
    definition: "definition",
    translation: "村子",
  },
  {
    id: "42",
    pos: "n/a",
    word: "vivir",
    definition: "definition",
    translation: "intr. 生活 生存",
  },
  {
    id: "43",
    pos: "n/a",
    word: "número de teléfono",
    definition: "definition",
    translation: "电话号码",
  },
  {
    id: "44",
    pos: "m.",
    word: "móvil",
    definition: "definition",
    translation: "手机",
  },
  {
    id: "45",
    pos: "n/a",
    word: "lugar de nacimiento",
    definition: "definition",
    translation: "出生地",
  },
  {
    id: "46",
    pos: "n/a",
    word: "fecha de nacimiento",
    definition: "definition",
    translation: "出生日期",
  },
  {
    id: "47",
    pos: "f.",
    word: "nacionalidad",
    definition: "definition",
    translation: "国籍",
  },
  {
    id: "48",
    pos: "adj.",
    word: "extranjero",
    definition: "definition",
    translation: "外国的m.,f. 外国人m. 外国",
  },
  {
    id: "49",
    pos: "adj.",
    word: "español",
    definition: "definition",
    translation: "西班牙的m.,f.  西班牙人m.  西班牙语",
  },
  {
    id: "50",
    pos: "adj.",
    word: "alemán",
    definition: "definition",
    translation: "德国的m.,f.  德国人m.  德语",
  },
  {
    id: "51",
    pos: "adj.",
    word: "mexicano",
    definition: "definition",
    translation: "墨西哥的m.,f.  墨西哥人",
  },
  {
    id: "52",
    pos: "adj.",
    word: "japonés",
    definition: "definition",
    translation: "日本的m.,f.  日本人m.  日语",
  },
  {
    id: "53",
    pos: "n/a",
    word: "ser de Laos",
    definition: "definition",
    translation: "是老挝人",
  },
  {
    id: "54",
    pos: "f.",
    word: "edad",
    definition: "definition",
    translation: "年龄",
  },
  {
    id: "55",
    pos: "m.",
    word: "niño",
    definition: "definition",
    translation: ",f. 儿童，孩子",
  },
  {
    id: "56",
    pos: "m.",
    word: "chico",
    definition: "definition",
    translation: ",f. 小孩  adj. 小的，年幼的",
  },
  {
    id: "57",
    pos: "adj.",
    word: "joven",
    definition: "definition",
    translation: "年轻的m.,f. 年轻人",
  },
  {
    id: "58",
    pos: "adj.",
    word: "viejo",
    definition: "definition",
    translation: "老的，旧的m.,f. 老人",
  },
  {
    id: "59",
    pos: "n/a",
    word: "tener 18 años",
    definition: "definition",
    translation: "18岁",
  },
  {
    id: "60",
    pos: "m.",
    word: "hombre",
    definition: "definition",
    translation: "男人",
  },
  {
    id: "61",
    pos: "f.",
    word: "mujer",
    definition: "definition",
    translation: "女人",
  },
  {
    id: "62",
    pos: "n/a",
    word: "estado civil",
    definition: "definition",
    translation: "婚姻状况",
  },
  {
    id: "63",
    pos: "adj.",
    word: "soltero",
    definition: "definition",
    translation: "单身的",
  },
  {
    id: "64",
    pos: "adj.",
    word: "casado",
    definition: "definition",
    translation: "已婚的",
  },
  {
    id: "65",
    pos: "adj.",
    word: "viudo",
    definition: "definition",
    translation: "丧偶的",
  },
  {
    id: "66",
    pos: "adj.",
    word: "separado",
    definition: "definition",
    translation: "分开的",
  },
  {
    id: "67",
    pos: "adj.",
    word: "divorciado",
    definition: "definition",
    translation: "离婚的",
  },
  {
    id: "68",
    pos: "f.",
    word: "llave",
    definition: "definition",
    translation: "钥匙",
  },
  {
    id: "69",
    pos: "f.",
    word: "cartera",
    definition: "definition",
    translation: "钱包",
  },
  {
    id: "70",
    pos: "m.",
    word: "reloj",
    definition: "definition",
    translation: "手表，时钟",
  },
  {
    id: "71",
    pos: "f.",
    word: "gafas",
    definition: "definition",
    translation: "[pl.] 眼镜",
  },
  {
    id: "72",
    pos: "f.",
    word: "familia",
    definition: "definition",
    translation: "家庭，家人",
  },
  {
    id: "73",
    pos: "m.",
    word: "padres",
    definition: "definition",
    translation: "[pl.] 父母",
  },
  {
    id: "74",
    pos: "m.",
    word: "padre",
    definition: "definition",
    translation: "父亲",
  },
  {
    id: "75",
    pos: "f.",
    word: "madre",
    definition: "definition",
    translation: "母亲",
  },
  {
    id: "76",
    pos: "m.",
    word: "hijo",
    definition: "definition",
    translation: ",f 子，女",
  },
  {
    id: "77",
    pos: "m.",
    word: "hermano",
    definition: "definition",
    translation: ",f 兄弟，姐妹",
  },
  {
    id: "78",
    pos: "m.",
    word: "tío",
    definition: "definition",
    translation: ",f  伯父, 叔父, 姑父, 舅父，姨父伯母， 婶母， 姑母， 舅母， 姨母",
  },
  {
    id: "79",
    pos: "m.",
    word: "sobrino",
    definition: "definition",
    translation: ",f 侄子，外甥，侄女, 外甥女",
  },
  {
    id: "80",
    pos: "m.",
    word: "abuelo",
    definition: "definition",
    translation: ",f. 爷爷，奶奶，姥爷，姥爷",
  },
  {
    id: "81",
    pos: "m.",
    word: "nieto",
    definition: "definition",
    translation: ",f. 孙子，孙女，外孙，外孙女",
  },
  {
    id: "82",
    pos: "m.",
    word: "primo",
    definition: "definition",
    translation: ",f. 表兄弟，表姐妹",
  },
  {
    id: "83",
    pos: "f.",
    word: "pareja",
    definition: "definition",
    translation: "伴侣",
  },
  {
    id: "84",
    pos: "m.",
    word: "novio",
    definition: "definition",
    translation: ",f. 男朋友，女朋友",
  },
  {
    id: "85",
    pos: "m.",
    word: "amigo",
    definition: "definition",
    translation: ",f. 朋友",
  },
  {
    id: "86",
    pos: "m.",
    word: "jefe",
    definition: "definition",
    translation: ",f. 老板，首领",
  },
  {
    id: "87",
    pos: "f.",
    word: "fiesta",
    definition: "definition",
    translation: "聚会",
  },
  {
    id: "88",
    pos: "m.",
    word: "desayuno",
    definition: "definition",
    translation: "早饭",
  },
  {
    id: "89",
    pos: "f.",
    word: "comida",
    definition: "definition",
    translation: "午饭，食物",
  },
  {
    id: "90",
    pos: "f.",
    word: "merienda",
    definition: "definition",
    translation: "午后小吃",
  },
  {
    id: "91",
    pos: "f.",
    word: "cena",
    definition: "definition",
    translation: "晚饭",
  },
  {
    id: "92",
    pos: "n/a",
    word: "desayunar",
    definition: "definition",
    translation: "intr.  吃早饭tr.吃…作为早饭",
  },
  {
    id: "93",
    pos: "n/a",
    word: "comer",
    definition: "definition",
    translation: "tr.-intr. 吃饭，吃午饭",
  },
  {
    id: "94",
    pos: "n/a",
    word: "merendar",
    definition: "definition",
    translation: "intr. 吃午后点心tr.吃…作为午后点心",
  },
  {
    id: "95",
    pos: "n/a",
    word: "cenar",
    definition: "definition",
    translation: "tr.-intr. 吃晚饭",
  },
  {
    id: "96",
    pos: "f.",
    word: "agua",
    definition: "definition",
    translation: "水",
  },
  {
    id: "97",
    pos: "n/a",
    word: "agua mineral",
    definition: "definition",
    translation: "矿泉水",
  },
  {
    id: "98",
    pos: "f.",
    word: "leche",
    definition: "definition",
    translation: "牛奶",
  },
  {
    id: "99",
    pos: "m.",
    word: "té",
    definition: "definition",
    translation: "茶",
  },
  {
    id: "100",
    pos: "m.",
    word: "café",
    definition: "definition",
    translation: "咖啡",
  },
  {
    id: "101",
    pos: "n/a",
    word: "café solo",
    definition: "definition",
    translation: "纯咖啡",
  },
  {
    id: "102",
    pos: "n/a",
    word: "café con leche",
    definition: "definition",
    translation: "牛奶咖啡",
  },
  {
    id: "103",
    pos: "n/a",
    word: "café cortado",
    definition: "definition",
    translation: "牛奶咖啡（多咖少奶）",
  },
  {
    id: "104",
    pos: "f.",
    word: "cerveza",
    definition: "definition",
    translation: "啤酒",
  },
  {
    id: "105",
    pos: "n/a",
    word: "vino blanco",
    definition: "definition",
    translation: "白葡萄酒",
  },
  {
    id: "106",
    pos: "n/a",
    word: "vino tinto",
    definition: "definition",
    translation: "红葡萄酒",
  },
  {
    id: "107",
    pos: "n/a",
    word: "beber",
    definition: "definition",
    translation: "intr. -tr. 喝",
  },
  {
    id: "108",
    pos: "f.",
    word: "carne",
    definition: "definition",
    translation: "肉",
  },
  {
    id: "109",
    pos: "m.",
    word: "pescado",
    definition: "definition",
    translation: "鱼",
  },
  {
    id: "110",
    pos: "f.",
    word: "fruta",
    definition: "definition",
    translation: "水果",
  },
  {
    id: "111",
    pos: "f.",
    word: "verdura",
    definition: "definition",
    translation: "蔬菜",
  },
  {
    id: "112",
    pos: "m.",
    word: "huevo",
    definition: "definition",
    translation: "鸡蛋",
  },
  {
    id: "113",
    pos: "m.",
    word: "pan",
    definition: "definition",
    translation: "面包",
  },
  {
    id: "114",
    pos: "m.",
    word: "bocadillo",
    definition: "definition",
    translation: "西班牙三明治",
  },
  {
    id: "115",
    pos: "m.",
    word: "sándwich",
    definition: "definition",
    translation: "三明治",
  },
  {
    id: "116",
    pos: "f.",
    word: "hamburguesa",
    definition: "definition",
    translation: "汉堡包",
  },
  {
    id: "117",
    pos: "n/a",
    word: "primer plato",
    definition: "definition",
    translation: "第一道菜",
  },
  {
    id: "118",
    pos: "n/a",
    word: "segundo plato",
    definition: "definition",
    translation: "第二道菜",
  },
  {
    id: "119",
    pos: "m.",
    word: "plato",
    definition: "definition",
    translation: "菜，盘子",
  },
  {
    id: "120",
    pos: "m.",
    word: "postre",
    definition: "definition",
    translation: "甜品",
  },
  {
    id: "121",
    pos: "f.",
    word: "sopa",
    definition: "definition",
    translation: "汤",
  },
  {
    id: "122",
    pos: "f.",
    word: "ensalada",
    definition: "definition",
    translation: "沙拉",
  },
  {
    id: "123",
    pos: "f.",
    word: "paella",
    definition: "definition",
    translation: "海鲜饭",
  },
  {
    id: "124",
    pos: "f.",
    word: "tortilla",
    definition: "definition",
    translation: "鸡蛋饼，玉米饼[拉美]",
  },
  {
    id: "125",
    pos: "m.",
    word: "bar",
    definition: "definition",
    translation: "酒吧",
  },
  {
    id: "126",
    pos: "m.",
    word: "restaurante",
    definition: "definition",
    translation: "餐厅",
  },
  {
    id: "127",
    pos: "m.",
    word: "camarero",
    definition: "definition",
    translation: ",f. 服务员  [拉美] mesero",
  },
  {
    id: "128",
    pos: "f.",
    word: "mesa",
    definition: "definition",
    translation: "桌子",
  },
  {
    id: "129",
    pos: "m.",
    word: "menú",
    definition: "definition",
    translation: "菜单",
  },
  {
    id: "130",
    pos: "f.",
    word: "cuenta",
    definition: "definition",
    translation: "账单",
  },
  {
    id: "131",
    pos: "m.",
    word: "instituto",
    definition: "definition",
    translation: "学院，协会",
  },
  {
    id: "132",
    pos: "f.",
    word: "universidad",
    definition: "definition",
    translation: "大学",
  },
  {
    id: "133",
    pos: "f.",
    word: "clase",
    definition: "definition",
    translation: "课程",
  },
  {
    id: "134",
    pos: "f.",
    word: "biblioteca",
    definition: "definition",
    translation: "图书馆",
  },
  {
    id: "135",
    pos: "m.",
    word: "profesor",
    definition: "definition",
    translation: ",f. 教师，教授",
  },
  {
    id: "136",
    pos: "m.",
    word: "estudiante",
    definition: "definition",
    translation: ",f. 学生",
  },
  {
    id: "137",
    pos: "m.",
    word: "director",
    definition: "definition",
    translation: ",f. 领导者，负责人",
  },
  {
    id: "138",
    pos: "m.",
    word: "compañero",
    definition: "definition",
    translation: ",f. 同伴，同学",
  },
  {
    id: "139",
    pos: "n/a",
    word: "clase de español",
    definition: "definition",
    translation: "西班牙语课",
  },
  {
    id: "140",
    pos: "m.",
    word: "examen",
    definition: "definition",
    translation: "考试",
  },
  {
    id: "141",
    pos: "n/a",
    word: "aprender",
    definition: "definition",
    translation: "tr. 学习，掌握",
  },
  {
    id: "142",
    pos: "n/a",
    word: "estudiar",
    definition: "definition",
    translation: "tr. 学",
  },
  {
    id: "143",
    pos: "n/a",
    word: "ir a clase",
    definition: "definition",
    translation: "去上课",
  },
  {
    id: "144",
    pos: "n/a",
    word: "hacer un examen",
    definition: "definition",
    translation: "参加一个考试",
  },
  {
    id: "145",
    pos: "m.",
    word: "ejercicio",
    definition: "definition",
    translation: "练习",
  },
  {
    id: "146",
    pos: "f.",
    word: "actividad",
    definition: "definition",
    translation: "活动",
  },
  {
    id: "147",
    pos: "f.",
    word: "lección",
    definition: "definition",
    translation: "课",
  },
  {
    id: "148",
    pos: "f.",
    word: "unidad",
    definition: "definition",
    translation: "单元",
  },
  {
    id: "149",
    pos: "f.",
    word: "página",
    definition: "definition",
    translation: "页",
  },
  {
    id: "150",
    pos: "f.",
    word: "pregunta",
    definition: "definition",
    translation: "问题",
  },
  {
    id: "151",
    pos: "n/a",
    word: "en parejas",
    definition: "definition",
    translation: "按两人一组，成对的",
  },
  {
    id: "152",
    pos: "n/a",
    word: "en grupos",
    definition: "definition",
    translation: "按组",
  },
  {
    id: "153",
    pos: "n/a",
    word: "hablar",
    definition: "definition",
    translation: "intr. 说话 tr. 会讲某种语言",
  },
  {
    id: "154",
    pos: "n/a",
    word: "leer",
    definition: "definition",
    translation: "tr. 阅读",
  },
  {
    id: "155",
    pos: "n/a",
    word: "escribir",
    definition: "definition",
    translation: "tr. 写",
  },
  {
    id: "156",
    pos: "n/a",
    word: "entender",
    definition: "definition",
    translation: "tr. 明白  intr. 懂得",
  },
  {
    id: "157",
    pos: "n/a",
    word: "comprender",
    definition: "definition",
    translation: "tr. 明白，理解",
  },
  {
    id: "158",
    pos: "n/a",
    word: "saber",
    definition: "definition",
    translation: "tr. 知道",
  },
  {
    id: "159",
    pos: "n/a",
    word: "repetir",
    definition: "definition",
    translation: "tr. 重复",
  },
  {
    id: "160",
    pos: "n/a",
    word: "practicar",
    definition: "definition",
    translation: "tr. 练习",
  },
  {
    id: "161",
    pos: "n/a",
    word: "hacer los deberes",
    definition: "definition",
    translation: "写作业",
  },
  {
    id: "162",
    pos: "n/a",
    word: "hacer un ejercicio",
    definition: "definition",
    translation: "做个练习",
  },
  {
    id: "163",
    pos: "m.",
    word: "internet",
    definition: "definition",
    translation: "互联网",
  },
  {
    id: "164",
    pos: "m.",
    word: "libro",
    definition: "definition",
    translation: "书",
  },
  {
    id: "165",
    pos: "m.",
    word: "diccionario",
    definition: "definition",
    translation: "字典",
  },
  {
    id: "166",
    pos: "m.",
    word: "papel",
    definition: "definition",
    translation: "纸",
  },
  {
    id: "167",
    pos: "m.",
    word: "bolígrafo",
    definition: "definition",
    translation: "圆珠笔  [墨西哥] lapicero",
  },
  {
    id: "168",
    pos: "m.",
    word: "lápiz",
    definition: "definition",
    translation: "铅笔",
  },
  {
    id: "169",
    pos: "f.",
    word: "goma",
    definition: "definition",
    translation: "橡皮",
  },
  {
    id: "170",
    pos: "f.",
    word: "fotocopia",
    definition: "definition",
    translation: "复印件",
  },
  {
    id: "171",
    pos: "f.",
    word: "silla",
    definition: "definition",
    translation: "椅子",
  },
  {
    id: "172",
    pos: "m.",
    word: "armario",
    definition: "definition",
    translation: "柜子",
  },
  {
    id: "173",
    pos: "f.",
    word: "estantería",
    definition: "definition",
    translation: "带隔板的家具",
  },
  {
    id: "174",
    pos: "f.",
    word: "pizarra",
    definition: "definition",
    translation: "黑板",
  },
  {
    id: "175",
    pos: "m.",
    word: "ordenador",
    definition: "definition",
    translation: "电脑  [拉美] computadora",
  },
  {
    id: "176",
    pos: "m.",
    word: "mapa",
    definition: "definition",
    translation: "地图",
  },
  {
    id: "177",
    pos: "m.",
    word: "abogado",
    definition: "definition",
    translation: ",f. 律师",
  },
  {
    id: "178",
    pos: "m.",
    word: "médico",
    definition: "definition",
    translation: ",f. 医生",
  },
  {
    id: "179",
    pos: "m.",
    word: "taxista",
    definition: "definition",
    translation: ",f. 出租车司机",
  },
  {
    id: "180",
    pos: "n/a",
    word: "ama de casa",
    definition: "definition",
    translation: "家庭主妇",
  },
  {
    id: "181",
    pos: "m.",
    word: "ingeniero",
    definition: "definition",
    translation: ",f. 工程师",
  },
  {
    id: "182",
    pos: "n/a",
    word: "dedicarse a",
    definition: "definition",
    translation: "从事…工作",
  },
  {
    id: "183",
    pos: "n/a",
    word: "lugar de trabajo",
    definition: "definition",
    translation: "工作地点",
  },
  {
    id: "184",
    pos: "f.",
    word: "empresa",
    definition: "definition",
    translation: "公司",
  },
  {
    id: "185",
    pos: "f.",
    word: "oficina",
    definition: "definition",
    translation: "办公室",
  },
  {
    id: "186",
    pos: "f.",
    word: "tienda",
    definition: "definition",
    translation: "商店",
  },
  {
    id: "187",
    pos: "m.",
    word: "teléfono",
    definition: "definition",
    translation: "电话",
  },
  {
    id: "188",
    pos: "m.",
    word: "fax",
    definition: "definition",
    translation: "传真",
  },
  {
    id: "189",
    pos: "m.",
    word: "trabajo",
    definition: "definition",
    translation: "工作",
  },
  {
    id: "190",
    pos: "f.",
    word: "profesión",
    definition: "definition",
    translation: "职业",
  },
  {
    id: "191",
    pos: "n/a",
    word: "comprar",
    definition: "definition",
    translation: "tr. 买",
  },
  {
    id: "192",
    pos: "n/a",
    word: "vender",
    definition: "definition",
    translation: "tr. 卖",
  },
  {
    id: "193",
    pos: "n/a",
    word: "estar en paro",
    definition: "definition",
    translation: "失业",
  },
  {
    id: "194",
    pos: "n/a",
    word: "trabajar",
    definition: "definition",
    translation: "intr. 工作",
  },
  {
    id: "195",
    pos: "f.",
    word: "vacaciones",
    definition: "definition",
    translation: "[pl.]假期",
  },
  {
    id: "196",
    pos: "m.",
    word: "turista",
    definition: "definition",
    translation: ",f. 游客",
  },
  {
    id: "197",
    pos: "n/a",
    word: "oficina de información",
    definition: "definition",
    translation: "信息咨询处",
  },
  {
    id: "198",
    pos: "n/a",
    word: "viajar",
    definition: "definition",
    translation: "intr. 旅游",
  },
  {
    id: "199",
    pos: "n/a",
    word: "leer el periódico",
    definition: "definition",
    translation: "读报纸",
  },
  {
    id: "200",
    pos: "n/a",
    word: "leer un libro",
    definition: "definition",
    translation: "读本书",
  },
  {
    id: "201",
    pos: "n/a",
    word: "leer una revista",
    definition: "definition",
    translation: "读本杂志",
  },
  {
    id: "202",
    pos: "n/a",
    word: "ver la televisión",
    definition: "definition",
    translation: "看电视",
  },
  {
    id: "203",
    pos: "n/a",
    word: "ver una película",
    definition: "definition",
    translation: "看一部电影",
  },
  {
    id: "204",
    pos: "n/a",
    word: "escuchar música",
    definition: "definition",
    translation: "听音乐",
  },
  {
    id: "205",
    pos: "n/a",
    word: "escuchar la radio",
    definition: "definition",
    translation: "听广播",
  },
  {
    id: "206",
    pos: "n/a",
    word: "escuchar una canción",
    definition: "definition",
    translation: "听首歌",
  },
  {
    id: "207",
    pos: "n/a",
    word: "ir a un café",
    definition: "definition",
    translation: "去家咖啡厅",
  },
  {
    id: "208",
    pos: "n/a",
    word: "ir a un restaurante",
    definition: "definition",
    translation: "去家餐厅",
  },
  {
    id: "209",
    pos: "n/a",
    word: "ir a un museo",
    definition: "definition",
    translation: "去家博物馆",
  },
  {
    id: "210",
    pos: "n/a",
    word: "ir al cine",
    definition: "definition",
    translation: "去电影院",
  },
  {
    id: "211",
    pos: "n/a",
    word: "ir al teatro",
    definition: "definition",
    translation: "去剧院",
  },
  {
    id: "212",
    pos: "n/a",
    word: "ir al parque",
    definition: "definition",
    translation: "去公园",
  },
  {
    id: "213",
    pos: "n/a",
    word: "ir al circo",
    definition: "definition",
    translation: "去看马戏",
  },
  {
    id: "214",
    pos: "n/a",
    word: "cantar",
    definition: "definition",
    translation: "intr. 唱歌",
  },
  {
    id: "215",
    pos: "n/a",
    word: "bailar",
    definition: "definition",
    translation: "intr. 跳舞",
  },
  {
    id: "216",
    pos: "f.",
    word: "película",
    definition: "definition",
    translation: "电影",
  },
  {
    id: "217",
    pos: "m.",
    word: "concierto",
    definition: "definition",
    translation: "音乐会",
  },
  {
    id: "218",
    pos: "n/a",
    word: "correr",
    definition: "definition",
    translation: "intr. 跑步",
  },
  {
    id: "219",
    pos: "n/a",
    word: "nadar",
    definition: "definition",
    translation: "intr. 游泳",
  },
  {
    id: "220",
    pos: "n/a",
    word: "esquiar",
    definition: "definition",
    translation: "intr. 滑雪",
  },
  {
    id: "221",
    pos: "n/a",
    word: "hacer deporte",
    definition: "definition",
    translation: "做体育运动",
  },
  {
    id: "222",
    pos: "n/a",
    word: "hacer ejercicio",
    definition: "definition",
    translation: "做运动",
  },
  {
    id: "223",
    pos: "n/a",
    word: "hacer gimnasia",
    definition: "definition",
    translation: "做体操",
  },
  {
    id: "224",
    pos: "n/a",
    word: "jugar al fútbol",
    definition: "definition",
    translation: "踢足球",
  },
  {
    id: "225",
    pos: "n/a",
    word: "jugar al baloncesto",
    definition: "definition",
    translation: "打篮球",
  },
  {
    id: "226",
    pos: "n/a",
    word: "jugar al tenis",
    definition: "definition",
    translation: "打网球",
  },
  {
    id: "227",
    pos: "m.",
    word: "juego",
    definition: "definition",
    translation: "游戏",
  },
  {
    id: "228",
    pos: "m.",
    word: "sobre",
    definition: "definition",
    translation: "信封",
  },
  {
    id: "229",
    pos: "m.",
    word: "sello",
    definition: "definition",
    translation: "印章",
  },
  {
    id: "230",
    pos: "n/a",
    word: "escribir una postal",
    definition: "definition",
    translation: "写张明信片",
  },
  {
    id: "231",
    pos: "n/a",
    word: "escribir una carta",
    definition: "definition",
    translation: "写封信",
  },
  {
    id: "232",
    pos: "n/a",
    word: "escribir un correo electrónico",
    definition: "definition",
    translation: "写封电子邮件",
  },
  {
    id: "233",
    pos: "n/a",
    word: "teléfono fijo",
    definition: "definition",
    translation: "固定电话",
  },
  {
    id: "234",
    pos: "m.",
    word: "quiosco",
    definition: "definition",
    translation: "报亭",
  },
  {
    id: "235",
    pos: "f.",
    word: "arroba",
    definition: "definition",
    translation: "@（艾特）",
  },
  {
    id: "236",
    pos: "m.",
    word: "guión",
    definition: "definition",
    translation: "连字符号[-]",
  },
  {
    id: "237",
    pos: "n/a",
    word: "guión bajo",
    definition: "definition",
    translation: "下划线",
  },
  {
    id: "238",
    pos: "m.",
    word: "punto",
    definition: "definition",
    translation: "句号，点",
  },
  {
    id: "239",
    pos: "n/a",
    word: "página web",
    definition: "definition",
    translation: "网页",
  },
  {
    id: "240",
    pos: "f.",
    word: "casa",
    definition: "definition",
    translation: "家",
  },
  {
    id: "241",
    pos: "m.",
    word: "piso",
    definition: "definition",
    translation: "公寓，地面，层",
  },
  {
    id: "242",
    pos: "m.",
    word: "apartamento",
    definition: "definition",
    translation: "公寓",
  },
  {
    id: "243",
    pos: "m.",
    word: "estudio",
    definition: "definition",
    translation: "单身公寓，工作室",
  },
  {
    id: "244",
    pos: "f.",
    word: "habitación",
    definition: "definition",
    translation: "房间",
  },
  {
    id: "245",
    pos: "m.",
    word: "ascensor",
    definition: "definition",
    translation: "电梯",
  },
  {
    id: "246",
    pos: "f.",
    word: "escalera",
    definition: "definition",
    translation: "楼梯",
  },
  {
    id: "247",
    pos: "f.",
    word: "terraza",
    definition: "definition",
    translation: "露台",
  },
  {
    id: "248",
    pos: "m.",
    word: "jardín",
    definition: "definition",
    translation: "花园",
  },
  {
    id: "249",
    pos: "f.",
    word: "ventana",
    definition: "definition",
    translation: "窗户",
  },
  {
    id: "250",
    pos: "f.",
    word: "puerta",
    definition: "definition",
    translation: "门",
  },
  {
    id: "251",
    pos: "n/a",
    word: "sala de estar",
    definition: "definition",
    translation: "客厅",
  },
  {
    id: "252",
    pos: "m.",
    word: "dormitorio",
    definition: "definition",
    translation: "寝室，宿舍",
  },
  {
    id: "253",
    pos: "f.",
    word: "cocina",
    definition: "definition",
    translation: "厨房",
  },
  {
    id: "254",
    pos: "m.",
    word: "baño",
    definition: "definition",
    translation: "卫生间",
  },
  {
    id: "255",
    pos: "m.",
    word: "salón",
    definition: "definition",
    translation: "大厅, 沙龙，展厅",
  },
  {
    id: "256",
    pos: "m.",
    word: "garaje",
    definition: "definition",
    translation: "车库",
  },
  {
    id: "257",
    pos: "n/a",
    word: "bien comunicado",
    definition: "definition",
    translation: "交通便利的",
  },
  {
    id: "258",
    pos: "n/a",
    word: "mal comunicado",
    definition: "definition",
    translation: "交通不便的",
  },
  {
    id: "259",
    pos: "n/a",
    word: "tener ascensor",
    definition: "definition",
    translation: "配有电梯",
  },
  {
    id: "260",
    pos: "n/a",
    word: "aire acondicionado",
    definition: "definition",
    translation: "空调",
  },
  {
    id: "261",
    pos: "f.",
    word: "calefacción",
    definition: "definition",
    translation: "暖气",
  },
  {
    id: "262",
    pos: "f.",
    word: "cama",
    definition: "definition",
    translation: "床",
  },
  {
    id: "263",
    pos: "m.",
    word: "sofá",
    definition: "definition",
    translation: "沙发",
  },
  {
    id: "264",
    pos: "m.",
    word: "sillón",
    definition: "definition",
    translation: "大扶手椅",
  },
  {
    id: "265",
    pos: "m.",
    word: "lavabo",
    definition: "definition",
    translation: "洗手间",
  },
  {
    id: "266",
    pos: "m.",
    word: "vídeo",
    definition: "definition",
    translation: "视频   [拉美]  video",
  },
  {
    id: "267",
    pos: "f.",
    word: "carta",
    definition: "definition",
    translation: "信",
  },
  {
    id: "268",
    pos: "f.",
    word: "postal",
    definition: "definition",
    translation: "明信片",
  },
  {
    id: "269",
    pos: "m.",
    word: "banco",
    definition: "definition",
    translation: "银行",
  },
  {
    id: "270",
    pos: "m.",
    word: "dinero",
    definition: "definition",
    translation: "钱",
  },
  {
    id: "271",
    pos: "m.",
    word: "euro",
    definition: "definition",
    translation: "欧元",
  },
  {
    id: "272",
    pos: "n/a",
    word: "cambiar dinero",
    definition: "definition",
    translation: "换钱",
  },
  {
    id: "273",
    pos: "m.",
    word: "hospital",
    definition: "definition",
    translation: "医院",
  },
  {
    id: "274",
    pos: "m.",
    word: "enfermera",
    definition: "definition",
    translation: ",f. 护士",
  },
  {
    id: "275",
    pos: "m.",
    word: "policía",
    definition: "definition",
    translation: ",f. 警察",
  },
  {
    id: "276",
    pos: "m.",
    word: "bombero",
    definition: "definition",
    translation: ",f. 消防员",
  },
  {
    id: "277",
    pos: "m.",
    word: "supermercado",
    definition: "definition",
    translation: "超市",
  },
  {
    id: "278",
    pos: "m.",
    word: "mercado",
    definition: "definition",
    translation: "市场",
  },
  {
    id: "279",
    pos: "f.",
    word: "entrada",
    definition: "definition",
    translation: "入口",
  },
  {
    id: "280",
    pos: "f.",
    word: "salida",
    definition: "definition",
    translation: "出口",
  },
  {
    id: "281",
    pos: "f.",
    word: "información",
    definition: "definition",
    translation: "信息",
  },
  {
    id: "282",
    pos: "m.",
    word: "comprador",
    definition: "definition",
    translation: ",f. 买家",
  },
  {
    id: "283",
    pos: "m.",
    word: "vendedor",
    definition: "definition",
    translation: ",f. 卖家",
  },
  {
    id: "284",
    pos: "m.",
    word: "pantalón",
    definition: "definition",
    translation: "裤子",
  },
  {
    id: "285",
    pos: "m.",
    word: "vaqueros",
    definition: "definition",
    translation: "[pl.]牛仔裤  [墨西哥] pantalónes de mezclilla",
  },
  {
    id: "286",
    pos: "f.",
    word: "falda",
    definition: "definition",
    translation: "半身裙",
  },
  {
    id: "287",
    pos: "f.",
    word: "camisa",
    definition: "definition",
    translation: "衬衫",
  },
  {
    id: "288",
    pos: "m.",
    word: "jersey",
    definition: "definition",
    translation: "针织衫，运动衫  [墨西哥] suéter",
  },
  {
    id: "289",
    pos: "m.",
    word: "zapatos",
    definition: "definition",
    translation: "[pl.] 鞋子",
  },
  {
    id: "290",
    pos: "m.",
    word: "bolso",
    definition: "definition",
    translation: "手提包",
  },
  {
    id: "291",
    pos: "m.",
    word: "precio",
    definition: "definition",
    translation: "价钱",
  },
  {
    id: "292",
    pos: "m.",
    word: "billete",
    definition: "definition",
    translation: "票，钱币  在[拉美]billete表示钱币，票则用boleto",
  },
  {
    id: "293",
    pos: "n/a",
    word: "pagar con tarjeta",
    definition: "definition",
    translation: "刷卡付款",
  },
  {
    id: "294",
    pos: "n/a",
    word: "tarjeta de crédito",
    definition: "definition",
    translation: "信用卡",
  },
  {
    id: "295",
    pos: "n/a",
    word: "estar enfermo",
    definition: "definition",
    translation: "生病",
  },
  {
    id: "296",
    pos: "n/a",
    word: "ir al hospital",
    definition: "definition",
    translation: "去医院",
  },
  {
    id: "297",
    pos: "n/a",
    word: "ir al médico",
    definition: "definition",
    translation: "去看医生",
  },
  {
    id: "298",
    pos: "f.",
    word: "farmacia",
    definition: "definition",
    translation: "药店",
  },
  {
    id: "299",
    pos: "m.",
    word: "jabón",
    definition: "definition",
    translation: "肥皂",
  },
  {
    id: "300",
    pos: "n/a",
    word: "lavarse la cara",
    definition: "definition",
    translation: "洗脸",
  },
  {
    id: "301",
    pos: "n/a",
    word: "lavarse las manos",
    definition: "definition",
    translation: "洗手",
  },
  {
    id: "302",
    pos: "n/a",
    word: "lavarse el pelo",
    definition: "definition",
    translation: "洗头",
  },
  {
    id: "303",
    pos: "n/a",
    word: "lavarse los dientes",
    definition: "definition",
    translation: "刷牙",
  },
  {
    id: "304",
    pos: "n/a",
    word: "ducharse",
    definition: "definition",
    translation: "prnl. 淋浴，洗澡",
  },
  {
    id: "305",
    pos: "n/a",
    word: "bañarse",
    definition: "definition",
    translation: "prnl. 沐浴，洗澡",
  },
  {
    id: "306",
    pos: "n/a",
    word: "carné de identidad",
    definition: "definition",
    translation: "身份证",
  },
  {
    id: "307",
    pos: "m.",
    word: "pasaporte",
    definition: "definition",
    translation: "护照",
  },
  {
    id: "308",
    pos: "n/a",
    word: "carné de conducir",
    definition: "definition",
    translation: "驾照  [墨西哥] licencia de manejo",
  },
  {
    id: "309",
    pos: "f.",
    word: "publicidad",
    definition: "definition",
    translation: "广告",
  },
  {
    id: "310",
    pos: "f.",
    word: "maleta",
    definition: "definition",
    translation: "行李箱",
  },
  {
    id: "311",
    pos: "n/a",
    word: "comprar un billete",
    definition: "definition",
    translation: "买一张票   [拉美] comprar un boleto",
  },
  {
    id: "312",
    pos: "n/a",
    word: "comprar un billete de ida",
    definition: "definition",
    translation: "买一张去程票  [拉美]comprar un boleto de ida",
  },
  {
    id: "313",
    pos: "n/a",
    word: "comprar un billete de ida y vuelta",
    definition: "definition",
    translation: "买往返票  [拉美]comprar un boleto de ida y vuelta",
  },
  {
    id: "314",
    pos: "m.",
    word: "horario",
    definition: "definition",
    translation: "时刻表",
  },
  {
    id: "315",
    pos: "n/a",
    word: "ir a Madrid",
    definition: "definition",
    translation: "去马德里",
  },
  {
    id: "316",
    pos: "n/a",
    word: "ir a la playa",
    definition: "definition",
    translation: "去海滩",
  },
  {
    id: "317",
    pos: "n/a",
    word: "ir a la montaña",
    definition: "definition",
    translation: "去山上",
  },
  {
    id: "318",
    pos: "m.",
    word: "hotel",
    definition: "definition",
    translation: "酒店",
  },
  {
    id: "319",
    pos: "m.",
    word: "camping",
    definition: "definition",
    translation: "野营",
  },
  {
    id: "320",
    pos: "n/a",
    word: "habitación doble",
    definition: "definition",
    translation: "双人间",
  },
  {
    id: "321",
    pos: "n/a",
    word: "habitación individual",
    definition: "definition",
    translation: "单人间",
  },
  {
    id: "322",
    pos: "f.",
    word: "carretera",
    definition: "definition",
    translation: "公路，大路",
  },
  {
    id: "323",
    pos: "m.",
    word: "aeropuerto",
    definition: "definition",
    translation: "飞机场",
  },
  {
    id: "324",
    pos: "m.",
    word: "puerto",
    definition: "definition",
    translation: "港口",
  },
  {
    id: "325",
    pos: "n/a",
    word: "estación de tren",
    definition: "definition",
    translation: "火车站",
  },
  {
    id: "326",
    pos: "n/a",
    word: "estación de metro",
    definition: "definition",
    translation: "地铁站",
  },
  {
    id: "327",
    pos: "n/a",
    word: "parada de autobús",
    definition: "definition",
    translation: "公交车站",
  },
  {
    id: "328",
    pos: "n/a",
    word: "parada de taxi",
    definition: "definition",
    translation: "出租车停靠站",
  },
  {
    id: "329",
    pos: "n/a",
    word: "ir andando",
    definition: "definition",
    translation: "走路去",
  },
  {
    id: "330",
    pos: "n/a",
    word: "ir en coche",
    definition: "definition",
    translation: "乘/开车去",
  },
  {
    id: "331",
    pos: "n/a",
    word: "ir en taxi",
    definition: "definition",
    translation: "乘坐出租车去",
  },
  {
    id: "332",
    pos: "n/a",
    word: "ir en tren",
    definition: "definition",
    translation: "坐火车去",
  },
  {
    id: "333",
    pos: "n/a",
    word: "ir en metro",
    definition: "definition",
    translation: "坐地铁去",
  },
  {
    id: "334",
    pos: "n/a",
    word: "ir en autobús",
    definition: "definition",
    translation: "坐公交车去",
  },
  {
    id: "335",
    pos: "n/a",
    word: "ir en avión",
    definition: "definition",
    translation: "坐飞机去",
  },
  {
    id: "336",
    pos: "n/a",
    word: "ir en barco",
    definition: "definition",
    translation: "乘船去",
  },
  {
    id: "337",
    pos: "m.",
    word: "conductor",
    definition: "definition",
    translation: ",f. 司机",
  },
  {
    id: "338",
    pos: "m.",
    word: "aparcamiento",
    definition: "definition",
    translation: "停车场",
  },
  {
    id: "339",
    pos: "n/a",
    word: "transporte por tierra",
    definition: "definition",
    translation: "陆地交通运输",
  },
  {
    id: "340",
    pos: "n/a",
    word: "transporte marítimo y fluvial",
    definition: "definition",
    translation: "海洋和河流交通运输",
  },
  {
    id: "341",
    pos: "n/a",
    word: "transporte aéreo",
    definition: "definition",
    translation: "航空交通运输",
  },
  {
    id: "342",
    pos: "adj.",
    word: "caro",
    definition: "definition",
    translation: "贵的",
  },
  {
    id: "343",
    pos: "adj.",
    word: "barato",
    definition: "definition",
    translation: "便宜的",
  },
  {
    id: "344",
    pos: "f.",
    word: "capital",
    definition: "definition",
    translation: "首都",
  },
  {
    id: "345",
    pos: "m.",
    word: "presidente",
    definition: "definition",
    translation: ",f. 主席，总统",
  },
  {
    id: "346",
    pos: "m.",
    word: "rey",
    definition: "definition",
    translation: "国王",
  },
  {
    id: "347",
    pos: "f.",
    word: "reina",
    definition: "definition",
    translation: "女王",
  },
  {
    id: "348",
    pos: "m.",
    word: "cine",
    definition: "definition",
    translation: "电影院",
  },
  {
    id: "349",
    pos: "m.",
    word: "teatro",
    definition: "definition",
    translation: "剧院",
  },
  {
    id: "350",
    pos: "f.",
    word: "música",
    definition: "definition",
    translation: "音乐",
  },
  {
    id: "351",
    pos: "f.",
    word: "foto",
    definition: "definition",
    translation: "照片",
  },
  {
    id: "352",
    pos: "m.",
    word: "museo",
    definition: "definition",
    translation: "博物馆",
  },
  {
    id: "353",
    pos: "f.",
    word: "exposición",
    definition: "definition",
    translation: "展览",
  },
  {
    id: "354",
    pos: "n/a",
    word: "ser interesante",
    definition: "definition",
    translation: "有意思",
  },
  {
    id: "355",
    pos: "m.",
    word: "cantante",
    definition: "definition",
    translation: ",f. 歌手",
  },
  {
    id: "356",
    pos: "m.",
    word: "edificio",
    definition: "definition",
    translation: "建筑物",
  },
  {
    id: "357",
    pos: "m.",
    word: "monumento",
    definition: "definition",
    translation: "纪念碑",
  },
  {
    id: "358",
    pos: "f.",
    word: "catedral",
    definition: "definition",
    translation: "大教堂",
  },
  {
    id: "359",
    pos: "f.",
    word: "iglesia",
    definition: "definition",
    translation: "教堂",
  },
  {
    id: "360",
    pos: "m.",
    word: "actor",
    definition: "definition",
    translation: "男演员",
  },
  {
    id: "361",
    pos: "f.",
    word: "actriz",
    definition: "definition",
    translation: "女演员",
  },
  {
    id: "362",
    pos: "f.",
    word: "religión",
    definition: "definition",
    translation: "宗教",
  },
  {
    id: "363",
    pos: "adj.",
    word: "cristiano",
    definition: "definition",
    translation: "基督教的m.,f.  基督教教徒",
  },
  {
    id: "364",
    pos: "adj.",
    word: "judío",
    definition: "definition",
    translation: "犹太人的m.,f. 犹太人 犹太教徒",
  },
  {
    id: "365",
    pos: "adj.",
    word: "musulmán",
    definition: "definition",
    translation: "穆斯林的m.,f.  穆斯林",
  },
  {
    id: "366",
    pos: "adj.",
    word: "budista",
    definition: "definition",
    translation: "佛教的m.,f.  佛教徒",
  },
  {
    id: "367",
    pos: "n/a",
    word: "ir a la iglesia",
    definition: "definition",
    translation: "去教堂",
  },
  {
    id: "368",
    pos: "n/a",
    word: "ir a la mezquita",
    definition: "definition",
    translation: "去清真寺",
  },
  {
    id: "369",
    pos: "n/a",
    word: "ir a la sinagoga",
    definition: "definition",
    translation: "去犹太教堂",
  },
  {
    id: "370",
    pos: "m.",
    word: "sol",
    definition: "definition",
    translation: "太阳",
  },
  {
    id: "371",
    pos: "m.",
    word: "lugar",
    definition: "definition",
    translation: "地方",
  },
  {
    id: "372",
    pos: "m.",
    word: "norte",
    definition: "definition",
    translation: "北部",
  },
  {
    id: "373",
    pos: "m.",
    word: "sur",
    definition: "definition",
    translation: "南部",
  },
  {
    id: "374",
    pos: "m.",
    word: "este",
    definition: "definition",
    translation: "东部",
  },
  {
    id: "375",
    pos: "m.",
    word: "oeste",
    definition: "definition",
    translation: "西部",
  },
  {
    id: "376",
    pos: "f.",
    word: "plaza",
    definition: "definition",
    translation: "广场",
  },
  {
    id: "377",
    pos: "n/a",
    word: "centro comercial",
    definition: "definition",
    translation: "购物中心",
  },
  {
    id: "378",
    pos: "m.",
    word: "colegio",
    definition: "definition",
    translation: "学院，学校",
  },
  {
    id: "379",
    pos: "f.",
    word: "escuela",
    definition: "definition",
    translation: "学校",
  },
  {
    id: "380",
    pos: "f.",
    word: "primavera",
    definition: "definition",
    translation: "春天",
  },
  {
    id: "381",
    pos: "m.",
    word: "verano",
    definition: "definition",
    translation: "夏天",
  },
  {
    id: "382",
    pos: "m.",
    word: "otoño",
    definition: "definition",
    translation: "秋天",
  },
  {
    id: "383",
    pos: "m.",
    word: "invierno",
    definition: "definition",
    translation: "冬天",
  },
  {
    id: "384",
    pos: "n/a",
    word: "llover",
    definition: "definition",
    translation: "impers.下雨",
  },
  {
    id: "385",
    pos: "n/a",
    word: "nevar",
    definition: "definition",
    translation: "impers.下雪",
  },
  {
    id: "386",
    pos: "n/a",
    word: "hace frío",
    definition: "definition",
    translation: "天气寒冷",
  },
  {
    id: "387",
    pos: "n/a",
    word: "hace calor",
    definition: "definition",
    translation: "天气炎热",
  },
  {
    id: "388",
    pos: "n/a",
    word: "hace sol",
    definition: "definition",
    translation: "阳光明媚",
  },
  {
    id: "389",
    pos: "n/a",
    word: "hace viento",
    definition: "definition",
    translation: "刮风",
  },
  {
    id: "390",
    pos: "n/a",
    word: "hace buen tiempo",
    definition: "definition",
    translation: "好天气",
  },
  {
    id: "391",
    pos: "n/a",
    word: "hace mal tiempo",
    definition: "definition",
    translation: "天气不好",
  },
  {
    id: "392",
    pos: "m.",
    word: "animal",
    definition: "definition",
    translation: "动物",
  },
  {
    id: "393",
    pos: "f.",
    word: "planta",
    definition: "definition",
    translation: "植物",
  },
  {
    id: "394",
    pos: "f.",
    word: "flor",
    definition: "definition",
    translation: "花",
  },
  {
    id: "395",
    pos: "m.",
    word: "árbol",
    definition: "definition",
    translation: "树",
  },
]);

//"普通高中西班牙语课程标准"
await db.insert(schema.wordInBook).values([
  {
    wb_id: "1",
    word_id: "1",
    word_index: 1,
  },
  {
    wb_id: "1",
    word_id: "2",
    word_index: 2,
  },
  {
    wb_id: "1",
    word_id: "3",
    word_index: 3,
  },
  {
    wb_id: "1",
    word_id: "4",
    word_index: 4,
  },
  {
    wb_id: "1",
    word_id: "5",
    word_index: 5,
  },
]);

//DELE A1
await db.insert(schema.wordInBook).values([
  {
    wb_id: "3",
    word_id: "1",
    word_index: 1,
  },
  {
    wb_id: "3",
    word_id: "2",
    word_index: 2,
  },
  {
    wb_id: "3",
    word_id: "3",
    word_index: 3,
  },
  {
    wb_id: "3",
    word_id: "4",
    word_index: 4,
  },
  {
    wb_id: "3",
    word_id: "5",
    word_index: 5,
  },
  {
    wb_id: "3",
    word_id: "6",
    word_index: 6,
  },
  {
    wb_id: "3",
    word_id: "7",
    word_index: 7,
  },
  {
    wb_id: "3",
    word_id: "8",
    word_index: 8,
  },
  {
    wb_id: "3",
    word_id: "9",
    word_index: 9,
  },
  {
    wb_id: "3",
    word_id: "10",
    word_index: 10,
  },
  {
    wb_id: "3",
    word_id: "11",
    word_index: 11,
  },
  {
    wb_id: "3",
    word_id: "12",
    word_index: 12,
  },
  {
    wb_id: "3",
    word_id: "13",
    word_index: 13,
  },
  {
    wb_id: "3",
    word_id: "14",
    word_index: 14,
  },
  {
    wb_id: "3",
    word_id: "15",
    word_index: 15,
  },
  {
    wb_id: "3",
    word_id: "16",
    word_index: 16,
  },
  {
    wb_id: "3",
    word_id: "17",
    word_index: 17,
  },
  {
    wb_id: "3",
    word_id: "18",
    word_index: 18,
  },
  {
    wb_id: "3",
    word_id: "19",
    word_index: 19,
  },
  {
    wb_id: "3",
    word_id: "20",
    word_index: 20,
  },
  {
    wb_id: "3",
    word_id: "21",
    word_index: 21,
  },
  {
    wb_id: "3",
    word_id: "22",
    word_index: 22,
  },
  {
    wb_id: "3",
    word_id: "23",
    word_index: 23,
  },
  {
    wb_id: "3",
    word_id: "24",
    word_index: 24,
  },
  {
    wb_id: "3",
    word_id: "25",
    word_index: 25,
  },
  {
    wb_id: "3",
    word_id: "26",
    word_index: 26,
  },
  {
    wb_id: "3",
    word_id: "27",
    word_index: 27,
  },
  {
    wb_id: "3",
    word_id: "28",
    word_index: 28,
  },
  {
    wb_id: "3",
    word_id: "29",
    word_index: 29,
  },
  {
    wb_id: "3",
    word_id: "30",
    word_index: 30,
  },
  {
    wb_id: "3",
    word_id: "31",
    word_index: 31,
  },
  {
    wb_id: "3",
    word_id: "32",
    word_index: 32,
  },
  {
    wb_id: "3",
    word_id: "33",
    word_index: 33,
  },
  {
    wb_id: "3",
    word_id: "34",
    word_index: 34,
  },
  {
    wb_id: "3",
    word_id: "35",
    word_index: 35,
  },
  {
    wb_id: "3",
    word_id: "36",
    word_index: 36,
  },
  {
    wb_id: "3",
    word_id: "37",
    word_index: 37,
  },
  {
    wb_id: "3",
    word_id: "38",
    word_index: 38,
  },
  {
    wb_id: "3",
    word_id: "39",
    word_index: 39,
  },
  {
    wb_id: "3",
    word_id: "40",
    word_index: 40,
  },
  {
    wb_id: "3",
    word_id: "41",
    word_index: 41,
  },
  {
    wb_id: "3",
    word_id: "42",
    word_index: 42,
  },
  {
    wb_id: "3",
    word_id: "43",
    word_index: 43,
  },
  {
    wb_id: "3",
    word_id: "44",
    word_index: 44,
  },
  {
    wb_id: "3",
    word_id: "45",
    word_index: 45,
  },
  {
    wb_id: "3",
    word_id: "46",
    word_index: 46,
  },
  {
    wb_id: "3",
    word_id: "47",
    word_index: 47,
  },
  {
    wb_id: "3",
    word_id: "48",
    word_index: 48,
  },
  {
    wb_id: "3",
    word_id: "49",
    word_index: 49,
  },
  {
    wb_id: "3",
    word_id: "50",
    word_index: 50,
  },
  {
    wb_id: "3",
    word_id: "51",
    word_index: 51,
  },
  {
    wb_id: "3",
    word_id: "52",
    word_index: 52,
  },
  {
    wb_id: "3",
    word_id: "53",
    word_index: 53,
  },
  {
    wb_id: "3",
    word_id: "54",
    word_index: 54,
  },
  {
    wb_id: "3",
    word_id: "55",
    word_index: 55,
  },
  {
    wb_id: "3",
    word_id: "56",
    word_index: 56,
  },
  {
    wb_id: "3",
    word_id: "57",
    word_index: 57,
  },
  {
    wb_id: "3",
    word_id: "58",
    word_index: 58,
  },
  {
    wb_id: "3",
    word_id: "59",
    word_index: 59,
  },
  {
    wb_id: "3",
    word_id: "60",
    word_index: 60,
  },
  {
    wb_id: "3",
    word_id: "61",
    word_index: 61,
  },
  {
    wb_id: "3",
    word_id: "62",
    word_index: 62,
  },
  {
    wb_id: "3",
    word_id: "63",
    word_index: 63,
  },
  {
    wb_id: "3",
    word_id: "64",
    word_index: 64,
  },
  {
    wb_id: "3",
    word_id: "65",
    word_index: 65,
  },
  {
    wb_id: "3",
    word_id: "66",
    word_index: 66,
  },
  {
    wb_id: "3",
    word_id: "67",
    word_index: 67,
  },
  {
    wb_id: "3",
    word_id: "68",
    word_index: 68,
  },
  {
    wb_id: "3",
    word_id: "69",
    word_index: 69,
  },
  {
    wb_id: "3",
    word_id: "70",
    word_index: 70,
  },
  {
    wb_id: "3",
    word_id: "71",
    word_index: 71,
  },
  {
    wb_id: "3",
    word_id: "72",
    word_index: 72,
  },
  {
    wb_id: "3",
    word_id: "73",
    word_index: 73,
  },
  {
    wb_id: "3",
    word_id: "74",
    word_index: 74,
  },
  {
    wb_id: "3",
    word_id: "75",
    word_index: 75,
  },
  {
    wb_id: "3",
    word_id: "76",
    word_index: 76,
  },
  {
    wb_id: "3",
    word_id: "77",
    word_index: 77,
  },
  {
    wb_id: "3",
    word_id: "78",
    word_index: 78,
  },
  {
    wb_id: "3",
    word_id: "79",
    word_index: 79,
  },
  {
    wb_id: "3",
    word_id: "80",
    word_index: 80,
  },
  {
    wb_id: "3",
    word_id: "81",
    word_index: 81,
  },
  {
    wb_id: "3",
    word_id: "82",
    word_index: 82,
  },
  {
    wb_id: "3",
    word_id: "83",
    word_index: 83,
  },
  {
    wb_id: "3",
    word_id: "84",
    word_index: 84,
  },
  {
    wb_id: "3",
    word_id: "85",
    word_index: 85,
  },
  {
    wb_id: "3",
    word_id: "86",
    word_index: 86,
  },
  {
    wb_id: "3",
    word_id: "87",
    word_index: 87,
  },
  {
    wb_id: "3",
    word_id: "88",
    word_index: 88,
  },
  {
    wb_id: "3",
    word_id: "89",
    word_index: 89,
  },
  {
    wb_id: "3",
    word_id: "90",
    word_index: 90,
  },
  {
    wb_id: "3",
    word_id: "91",
    word_index: 91,
  },
  {
    wb_id: "3",
    word_id: "92",
    word_index: 92,
  },
  {
    wb_id: "3",
    word_id: "93",
    word_index: 93,
  },
  {
    wb_id: "3",
    word_id: "94",
    word_index: 94,
  },
  {
    wb_id: "3",
    word_id: "95",
    word_index: 95,
  },
  {
    wb_id: "3",
    word_id: "96",
    word_index: 96,
  },
  {
    wb_id: "3",
    word_id: "97",
    word_index: 97,
  },
  {
    wb_id: "3",
    word_id: "98",
    word_index: 98,
  },
  {
    wb_id: "3",
    word_id: "99",
    word_index: 99,
  },
  {
    wb_id: "3",
    word_id: "100",
    word_index: 100,
  },
  {
    wb_id: "3",
    word_id: "101",
    word_index: 101,
  },
  {
    wb_id: "3",
    word_id: "102",
    word_index: 102,
  },
  {
    wb_id: "3",
    word_id: "103",
    word_index: 103,
  },
  {
    wb_id: "3",
    word_id: "104",
    word_index: 104,
  },
  {
    wb_id: "3",
    word_id: "105",
    word_index: 105,
  },
  {
    wb_id: "3",
    word_id: "106",
    word_index: 106,
  },
  {
    wb_id: "3",
    word_id: "107",
    word_index: 107,
  },
  {
    wb_id: "3",
    word_id: "108",
    word_index: 108,
  },
  {
    wb_id: "3",
    word_id: "109",
    word_index: 109,
  },
  {
    wb_id: "3",
    word_id: "110",
    word_index: 110,
  },
  {
    wb_id: "3",
    word_id: "111",
    word_index: 111,
  },
  {
    wb_id: "3",
    word_id: "112",
    word_index: 112,
  },
  {
    wb_id: "3",
    word_id: "113",
    word_index: 113,
  },
  {
    wb_id: "3",
    word_id: "114",
    word_index: 114,
  },
  {
    wb_id: "3",
    word_id: "115",
    word_index: 115,
  },
  {
    wb_id: "3",
    word_id: "116",
    word_index: 116,
  },
  {
    wb_id: "3",
    word_id: "117",
    word_index: 117,
  },
  {
    wb_id: "3",
    word_id: "118",
    word_index: 118,
  },
  {
    wb_id: "3",
    word_id: "119",
    word_index: 119,
  },
  {
    wb_id: "3",
    word_id: "120",
    word_index: 120,
  },
  {
    wb_id: "3",
    word_id: "121",
    word_index: 121,
  },
  {
    wb_id: "3",
    word_id: "122",
    word_index: 122,
  },
  {
    wb_id: "3",
    word_id: "123",
    word_index: 123,
  },
  {
    wb_id: "3",
    word_id: "124",
    word_index: 124,
  },
  {
    wb_id: "3",
    word_id: "125",
    word_index: 125,
  },
  {
    wb_id: "3",
    word_id: "126",
    word_index: 126,
  },
  {
    wb_id: "3",
    word_id: "127",
    word_index: 127,
  },
  {
    wb_id: "3",
    word_id: "128",
    word_index: 128,
  },
  {
    wb_id: "3",
    word_id: "129",
    word_index: 129,
  },
  {
    wb_id: "3",
    word_id: "130",
    word_index: 130,
  },
  {
    wb_id: "3",
    word_id: "131",
    word_index: 131,
  },
  {
    wb_id: "3",
    word_id: "132",
    word_index: 132,
  },
  {
    wb_id: "3",
    word_id: "133",
    word_index: 133,
  },
  {
    wb_id: "3",
    word_id: "134",
    word_index: 134,
  },
  {
    wb_id: "3",
    word_id: "135",
    word_index: 135,
  },
  {
    wb_id: "3",
    word_id: "136",
    word_index: 136,
  },
  {
    wb_id: "3",
    word_id: "137",
    word_index: 137,
  },
  {
    wb_id: "3",
    word_id: "138",
    word_index: 138,
  },
  {
    wb_id: "3",
    word_id: "139",
    word_index: 139,
  },
  {
    wb_id: "3",
    word_id: "140",
    word_index: 140,
  },
  {
    wb_id: "3",
    word_id: "141",
    word_index: 141,
  },
  {
    wb_id: "3",
    word_id: "142",
    word_index: 142,
  },
  {
    wb_id: "3",
    word_id: "143",
    word_index: 143,
  },
  {
    wb_id: "3",
    word_id: "144",
    word_index: 144,
  },
  {
    wb_id: "3",
    word_id: "145",
    word_index: 145,
  },
  {
    wb_id: "3",
    word_id: "146",
    word_index: 146,
  },
  {
    wb_id: "3",
    word_id: "147",
    word_index: 147,
  },
  {
    wb_id: "3",
    word_id: "148",
    word_index: 148,
  },
  {
    wb_id: "3",
    word_id: "149",
    word_index: 149,
  },
  {
    wb_id: "3",
    word_id: "150",
    word_index: 150,
  },
  {
    wb_id: "3",
    word_id: "151",
    word_index: 151,
  },
  {
    wb_id: "3",
    word_id: "152",
    word_index: 152,
  },
  {
    wb_id: "3",
    word_id: "153",
    word_index: 153,
  },
  {
    wb_id: "3",
    word_id: "154",
    word_index: 154,
  },
  {
    wb_id: "3",
    word_id: "155",
    word_index: 155,
  },
  {
    wb_id: "3",
    word_id: "156",
    word_index: 156,
  },
  {
    wb_id: "3",
    word_id: "157",
    word_index: 157,
  },
  {
    wb_id: "3",
    word_id: "158",
    word_index: 158,
  },
  {
    wb_id: "3",
    word_id: "159",
    word_index: 159,
  },
  {
    wb_id: "3",
    word_id: "160",
    word_index: 160,
  },
  {
    wb_id: "3",
    word_id: "161",
    word_index: 161,
  },
  {
    wb_id: "3",
    word_id: "162",
    word_index: 162,
  },
  {
    wb_id: "3",
    word_id: "163",
    word_index: 163,
  },
  {
    wb_id: "3",
    word_id: "164",
    word_index: 164,
  },
  {
    wb_id: "3",
    word_id: "165",
    word_index: 165,
  },
  {
    wb_id: "3",
    word_id: "166",
    word_index: 166,
  },
  {
    wb_id: "3",
    word_id: "167",
    word_index: 167,
  },
  {
    wb_id: "3",
    word_id: "168",
    word_index: 168,
  },
  {
    wb_id: "3",
    word_id: "169",
    word_index: 169,
  },
  {
    wb_id: "3",
    word_id: "170",
    word_index: 170,
  },
  {
    wb_id: "3",
    word_id: "171",
    word_index: 171,
  },
  {
    wb_id: "3",
    word_id: "172",
    word_index: 172,
  },
  {
    wb_id: "3",
    word_id: "173",
    word_index: 173,
  },
  {
    wb_id: "3",
    word_id: "174",
    word_index: 174,
  },
  {
    wb_id: "3",
    word_id: "175",
    word_index: 175,
  },
  {
    wb_id: "3",
    word_id: "176",
    word_index: 176,
  },
  {
    wb_id: "3",
    word_id: "177",
    word_index: 177,
  },
  {
    wb_id: "3",
    word_id: "178",
    word_index: 178,
  },
  {
    wb_id: "3",
    word_id: "179",
    word_index: 179,
  },
  {
    wb_id: "3",
    word_id: "180",
    word_index: 180,
  },
  {
    wb_id: "3",
    word_id: "181",
    word_index: 181,
  },
  {
    wb_id: "3",
    word_id: "182",
    word_index: 182,
  },
  {
    wb_id: "3",
    word_id: "183",
    word_index: 183,
  },
  {
    wb_id: "3",
    word_id: "184",
    word_index: 184,
  },
  {
    wb_id: "3",
    word_id: "185",
    word_index: 185,
  },
  {
    wb_id: "3",
    word_id: "186",
    word_index: 186,
  },
  {
    wb_id: "3",
    word_id: "187",
    word_index: 187,
  },
  {
    wb_id: "3",
    word_id: "188",
    word_index: 188,
  },
  {
    wb_id: "3",
    word_id: "189",
    word_index: 189,
  },
  {
    wb_id: "3",
    word_id: "190",
    word_index: 190,
  },
  {
    wb_id: "3",
    word_id: "191",
    word_index: 191,
  },
  {
    wb_id: "3",
    word_id: "192",
    word_index: 192,
  },
  {
    wb_id: "3",
    word_id: "193",
    word_index: 193,
  },
  {
    wb_id: "3",
    word_id: "194",
    word_index: 194,
  },
  {
    wb_id: "3",
    word_id: "195",
    word_index: 195,
  },
  {
    wb_id: "3",
    word_id: "196",
    word_index: 196,
  },
  {
    wb_id: "3",
    word_id: "197",
    word_index: 197,
  },
  {
    wb_id: "3",
    word_id: "198",
    word_index: 198,
  },
  {
    wb_id: "3",
    word_id: "199",
    word_index: 199,
  },
  {
    wb_id: "3",
    word_id: "200",
    word_index: 200,
  },
  {
    wb_id: "3",
    word_id: "201",
    word_index: 201,
  },
  {
    wb_id: "3",
    word_id: "202",
    word_index: 202,
  },
  {
    wb_id: "3",
    word_id: "203",
    word_index: 203,
  },
  {
    wb_id: "3",
    word_id: "204",
    word_index: 204,
  },
  {
    wb_id: "3",
    word_id: "205",
    word_index: 205,
  },
  {
    wb_id: "3",
    word_id: "206",
    word_index: 206,
  },
  {
    wb_id: "3",
    word_id: "207",
    word_index: 207,
  },
  {
    wb_id: "3",
    word_id: "208",
    word_index: 208,
  },
  {
    wb_id: "3",
    word_id: "209",
    word_index: 209,
  },
  {
    wb_id: "3",
    word_id: "210",
    word_index: 210,
  },
  {
    wb_id: "3",
    word_id: "211",
    word_index: 211,
  },
  {
    wb_id: "3",
    word_id: "212",
    word_index: 212,
  },
  {
    wb_id: "3",
    word_id: "213",
    word_index: 213,
  },
  {
    wb_id: "3",
    word_id: "214",
    word_index: 214,
  },
  {
    wb_id: "3",
    word_id: "215",
    word_index: 215,
  },
  {
    wb_id: "3",
    word_id: "216",
    word_index: 216,
  },
  {
    wb_id: "3",
    word_id: "217",
    word_index: 217,
  },
  {
    wb_id: "3",
    word_id: "218",
    word_index: 218,
  },
  {
    wb_id: "3",
    word_id: "219",
    word_index: 219,
  },
  {
    wb_id: "3",
    word_id: "220",
    word_index: 220,
  },
  {
    wb_id: "3",
    word_id: "221",
    word_index: 221,
  },
  {
    wb_id: "3",
    word_id: "222",
    word_index: 222,
  },
  {
    wb_id: "3",
    word_id: "223",
    word_index: 223,
  },
  {
    wb_id: "3",
    word_id: "224",
    word_index: 224,
  },
  {
    wb_id: "3",
    word_id: "225",
    word_index: 225,
  },
  {
    wb_id: "3",
    word_id: "226",
    word_index: 226,
  },
  {
    wb_id: "3",
    word_id: "227",
    word_index: 227,
  },
  {
    wb_id: "3",
    word_id: "228",
    word_index: 228,
  },
  {
    wb_id: "3",
    word_id: "229",
    word_index: 229,
  },
  {
    wb_id: "3",
    word_id: "230",
    word_index: 230,
  },
  {
    wb_id: "3",
    word_id: "231",
    word_index: 231,
  },
  {
    wb_id: "3",
    word_id: "232",
    word_index: 232,
  },
  {
    wb_id: "3",
    word_id: "233",
    word_index: 233,
  },
  {
    wb_id: "3",
    word_id: "234",
    word_index: 234,
  },
  {
    wb_id: "3",
    word_id: "235",
    word_index: 235,
  },
  {
    wb_id: "3",
    word_id: "236",
    word_index: 236,
  },
  {
    wb_id: "3",
    word_id: "237",
    word_index: 237,
  },
  {
    wb_id: "3",
    word_id: "238",
    word_index: 238,
  },
  {
    wb_id: "3",
    word_id: "239",
    word_index: 239,
  },
  {
    wb_id: "3",
    word_id: "240",
    word_index: 240,
  },
  {
    wb_id: "3",
    word_id: "241",
    word_index: 241,
  },
  {
    wb_id: "3",
    word_id: "242",
    word_index: 242,
  },
  {
    wb_id: "3",
    word_id: "243",
    word_index: 243,
  },
  {
    wb_id: "3",
    word_id: "244",
    word_index: 244,
  },
  {
    wb_id: "3",
    word_id: "245",
    word_index: 245,
  },
  {
    wb_id: "3",
    word_id: "246",
    word_index: 246,
  },
  {
    wb_id: "3",
    word_id: "247",
    word_index: 247,
  },
  {
    wb_id: "3",
    word_id: "248",
    word_index: 248,
  },
  {
    wb_id: "3",
    word_id: "249",
    word_index: 249,
  },
  {
    wb_id: "3",
    word_id: "250",
    word_index: 250,
  },
  {
    wb_id: "3",
    word_id: "251",
    word_index: 251,
  },
  {
    wb_id: "3",
    word_id: "252",
    word_index: 252,
  },
  {
    wb_id: "3",
    word_id: "253",
    word_index: 253,
  },
  {
    wb_id: "3",
    word_id: "254",
    word_index: 254,
  },
  {
    wb_id: "3",
    word_id: "255",
    word_index: 255,
  },
  {
    wb_id: "3",
    word_id: "256",
    word_index: 256,
  },
  {
    wb_id: "3",
    word_id: "257",
    word_index: 257,
  },
  {
    wb_id: "3",
    word_id: "258",
    word_index: 258,
  },
  {
    wb_id: "3",
    word_id: "259",
    word_index: 259,
  },
  {
    wb_id: "3",
    word_id: "260",
    word_index: 260,
  },
  {
    wb_id: "3",
    word_id: "261",
    word_index: 261,
  },
  {
    wb_id: "3",
    word_id: "262",
    word_index: 262,
  },
  {
    wb_id: "3",
    word_id: "263",
    word_index: 263,
  },
  {
    wb_id: "3",
    word_id: "264",
    word_index: 264,
  },
  {
    wb_id: "3",
    word_id: "265",
    word_index: 265,
  },
  {
    wb_id: "3",
    word_id: "266",
    word_index: 266,
  },
  {
    wb_id: "3",
    word_id: "267",
    word_index: 267,
  },
  {
    wb_id: "3",
    word_id: "268",
    word_index: 268,
  },
  {
    wb_id: "3",
    word_id: "269",
    word_index: 269,
  },
  {
    wb_id: "3",
    word_id: "270",
    word_index: 270,
  },
  {
    wb_id: "3",
    word_id: "271",
    word_index: 271,
  },
  {
    wb_id: "3",
    word_id: "272",
    word_index: 272,
  },
  {
    wb_id: "3",
    word_id: "273",
    word_index: 273,
  },
  {
    wb_id: "3",
    word_id: "274",
    word_index: 274,
  },
  {
    wb_id: "3",
    word_id: "275",
    word_index: 275,
  },
  {
    wb_id: "3",
    word_id: "276",
    word_index: 276,
  },
  {
    wb_id: "3",
    word_id: "277",
    word_index: 277,
  },
  {
    wb_id: "3",
    word_id: "278",
    word_index: 278,
  },
  {
    wb_id: "3",
    word_id: "279",
    word_index: 279,
  },
  {
    wb_id: "3",
    word_id: "280",
    word_index: 280,
  },
  {
    wb_id: "3",
    word_id: "281",
    word_index: 281,
  },
  {
    wb_id: "3",
    word_id: "282",
    word_index: 282,
  },
  {
    wb_id: "3",
    word_id: "283",
    word_index: 283,
  },
  {
    wb_id: "3",
    word_id: "284",
    word_index: 284,
  },
  {
    wb_id: "3",
    word_id: "285",
    word_index: 285,
  },
  {
    wb_id: "3",
    word_id: "286",
    word_index: 286,
  },
  {
    wb_id: "3",
    word_id: "287",
    word_index: 287,
  },
  {
    wb_id: "3",
    word_id: "288",
    word_index: 288,
  },
  {
    wb_id: "3",
    word_id: "289",
    word_index: 289,
  },
  {
    wb_id: "3",
    word_id: "290",
    word_index: 290,
  },
  {
    wb_id: "3",
    word_id: "291",
    word_index: 291,
  },
  {
    wb_id: "3",
    word_id: "292",
    word_index: 292,
  },
  {
    wb_id: "3",
    word_id: "293",
    word_index: 293,
  },
  {
    wb_id: "3",
    word_id: "294",
    word_index: 294,
  },
  {
    wb_id: "3",
    word_id: "295",
    word_index: 295,
  },
  {
    wb_id: "3",
    word_id: "296",
    word_index: 296,
  },
  {
    wb_id: "3",
    word_id: "297",
    word_index: 297,
  },
  {
    wb_id: "3",
    word_id: "298",
    word_index: 298,
  },
  {
    wb_id: "3",
    word_id: "299",
    word_index: 299,
  },
  {
    wb_id: "3",
    word_id: "300",
    word_index: 300,
  },
  {
    wb_id: "3",
    word_id: "301",
    word_index: 301,
  },
  {
    wb_id: "3",
    word_id: "302",
    word_index: 302,
  },
  {
    wb_id: "3",
    word_id: "303",
    word_index: 303,
  },
  {
    wb_id: "3",
    word_id: "304",
    word_index: 304,
  },
  {
    wb_id: "3",
    word_id: "305",
    word_index: 305,
  },
  {
    wb_id: "3",
    word_id: "306",
    word_index: 306,
  },
  {
    wb_id: "3",
    word_id: "307",
    word_index: 307,
  },
  {
    wb_id: "3",
    word_id: "308",
    word_index: 308,
  },
  {
    wb_id: "3",
    word_id: "309",
    word_index: 309,
  },
  {
    wb_id: "3",
    word_id: "310",
    word_index: 310,
  },
  {
    wb_id: "3",
    word_id: "311",
    word_index: 311,
  },
  {
    wb_id: "3",
    word_id: "312",
    word_index: 312,
  },
  {
    wb_id: "3",
    word_id: "313",
    word_index: 313,
  },
  {
    wb_id: "3",
    word_id: "314",
    word_index: 314,
  },
  {
    wb_id: "3",
    word_id: "315",
    word_index: 315,
  },
  {
    wb_id: "3",
    word_id: "316",
    word_index: 316,
  },
  {
    wb_id: "3",
    word_id: "317",
    word_index: 317,
  },
  {
    wb_id: "3",
    word_id: "318",
    word_index: 318,
  },
  {
    wb_id: "3",
    word_id: "319",
    word_index: 319,
  },
  {
    wb_id: "3",
    word_id: "320",
    word_index: 320,
  },
  {
    wb_id: "3",
    word_id: "321",
    word_index: 321,
  },
  {
    wb_id: "3",
    word_id: "322",
    word_index: 322,
  },
  {
    wb_id: "3",
    word_id: "323",
    word_index: 323,
  },
  {
    wb_id: "3",
    word_id: "324",
    word_index: 324,
  },
  {
    wb_id: "3",
    word_id: "325",
    word_index: 325,
  },
  {
    wb_id: "3",
    word_id: "326",
    word_index: 326,
  },
  {
    wb_id: "3",
    word_id: "327",
    word_index: 327,
  },
  {
    wb_id: "3",
    word_id: "328",
    word_index: 328,
  },
  {
    wb_id: "3",
    word_id: "329",
    word_index: 329,
  },
  {
    wb_id: "3",
    word_id: "330",
    word_index: 330,
  },
  {
    wb_id: "3",
    word_id: "331",
    word_index: 331,
  },
  {
    wb_id: "3",
    word_id: "332",
    word_index: 332,
  },
  {
    wb_id: "3",
    word_id: "333",
    word_index: 333,
  },
  {
    wb_id: "3",
    word_id: "334",
    word_index: 334,
  },
  {
    wb_id: "3",
    word_id: "335",
    word_index: 335,
  },
  {
    wb_id: "3",
    word_id: "336",
    word_index: 336,
  },
  {
    wb_id: "3",
    word_id: "337",
    word_index: 337,
  },
  {
    wb_id: "3",
    word_id: "338",
    word_index: 338,
  },
  {
    wb_id: "3",
    word_id: "339",
    word_index: 339,
  },
  {
    wb_id: "3",
    word_id: "340",
    word_index: 340,
  },
  {
    wb_id: "3",
    word_id: "341",
    word_index: 341,
  },
  {
    wb_id: "3",
    word_id: "342",
    word_index: 342,
  },
  {
    wb_id: "3",
    word_id: "343",
    word_index: 343,
  },
  {
    wb_id: "3",
    word_id: "344",
    word_index: 344,
  },
  {
    wb_id: "3",
    word_id: "345",
    word_index: 345,
  },
  {
    wb_id: "3",
    word_id: "346",
    word_index: 346,
  },
  {
    wb_id: "3",
    word_id: "347",
    word_index: 347,
  },
  {
    wb_id: "3",
    word_id: "348",
    word_index: 348,
  },
  {
    wb_id: "3",
    word_id: "349",
    word_index: 349,
  },
  {
    wb_id: "3",
    word_id: "350",
    word_index: 350,
  },
  {
    wb_id: "3",
    word_id: "351",
    word_index: 351,
  },
  {
    wb_id: "3",
    word_id: "352",
    word_index: 352,
  },
  {
    wb_id: "3",
    word_id: "353",
    word_index: 353,
  },
  {
    wb_id: "3",
    word_id: "354",
    word_index: 354,
  },
  {
    wb_id: "3",
    word_id: "355",
    word_index: 355,
  },
  {
    wb_id: "3",
    word_id: "356",
    word_index: 356,
  },
  {
    wb_id: "3",
    word_id: "357",
    word_index: 357,
  },
  {
    wb_id: "3",
    word_id: "358",
    word_index: 358,
  },
  {
    wb_id: "3",
    word_id: "359",
    word_index: 359,
  },
  {
    wb_id: "3",
    word_id: "360",
    word_index: 360,
  },
  {
    wb_id: "3",
    word_id: "361",
    word_index: 361,
  },
  {
    wb_id: "3",
    word_id: "362",
    word_index: 362,
  },
  {
    wb_id: "3",
    word_id: "363",
    word_index: 363,
  },
  {
    wb_id: "3",
    word_id: "364",
    word_index: 364,
  },
  {
    wb_id: "3",
    word_id: "365",
    word_index: 365,
  },
  {
    wb_id: "3",
    word_id: "366",
    word_index: 366,
  },
  {
    wb_id: "3",
    word_id: "367",
    word_index: 367,
  },
  {
    wb_id: "3",
    word_id: "368",
    word_index: 368,
  },
  {
    wb_id: "3",
    word_id: "369",
    word_index: 369,
  },
  {
    wb_id: "3",
    word_id: "370",
    word_index: 370,
  },
  {
    wb_id: "3",
    word_id: "371",
    word_index: 371,
  },
  {
    wb_id: "3",
    word_id: "372",
    word_index: 372,
  },
  {
    wb_id: "3",
    word_id: "373",
    word_index: 373,
  },
  {
    wb_id: "3",
    word_id: "374",
    word_index: 374,
  },
  {
    wb_id: "3",
    word_id: "375",
    word_index: 375,
  },
  {
    wb_id: "3",
    word_id: "376",
    word_index: 376,
  },
  {
    wb_id: "3",
    word_id: "377",
    word_index: 377,
  },
  {
    wb_id: "3",
    word_id: "378",
    word_index: 378,
  },
  {
    wb_id: "3",
    word_id: "379",
    word_index: 379,
  },
  {
    wb_id: "3",
    word_id: "380",
    word_index: 380,
  },
  {
    wb_id: "3",
    word_id: "381",
    word_index: 381,
  },
  {
    wb_id: "3",
    word_id: "382",
    word_index: 382,
  },
  {
    wb_id: "3",
    word_id: "383",
    word_index: 383,
  },
  {
    wb_id: "3",
    word_id: "384",
    word_index: 384,
  },
  {
    wb_id: "3",
    word_id: "385",
    word_index: 385,
  },
  {
    wb_id: "3",
    word_id: "386",
    word_index: 386,
  },
  {
    wb_id: "3",
    word_id: "387",
    word_index: 387,
  },
  {
    wb_id: "3",
    word_id: "388",
    word_index: 388,
  },
  {
    wb_id: "3",
    word_id: "389",
    word_index: 389,
  },
  {
    wb_id: "3",
    word_id: "390",
    word_index: 390,
  },
  {
    wb_id: "3",
    word_id: "391",
    word_index: 391,
  },
  {
    wb_id: "3",
    word_id: "392",
    word_index: 392,
  },
  {
    wb_id: "3",
    word_id: "393",
    word_index: 393,
  },
  {
    wb_id: "3",
    word_id: "394",
    word_index: 394,
  },
  {
    wb_id: "3",
    word_id: "395",
    word_index: 395,
  }
]);

console.log("Seeding complete.");
